danceclassappv1/config/routes.rb
Rails.application.routes.draw do
    get 'd_class/list' => 'd_class#list'
    resources :d_class
    root 'static_pages#home'
    
  

end

danceclassappv1/app/models/d_class.rb
class DClass < ActiveRecord::Base

	validates :dancetype, presence:true
	validates :day, presence:true
	validates :location, presence:true

  def self.search(search)
        #@searchresult = DClass.where(dancetype: search)  
        @searchresult = DClass.where(dancetype: search)
  end


end

danceclassappv1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

danceclassappv1/app/controllers/d_class_controller.rb
class DClassController < ApplicationController
  def new
    @dclass = DClass.new
  end

  def create
    @dclass = DClass.new(dclass_params)
    if @dclass.save
      flash[:success] = "New class successfully added!"
      redirect_to @dclass
    else
      render 'new'
    end
  end

  #def list
   # @dclass = DClass.search(params[:search])
    #render 'list'
  #end

  def list
    @dclass = DClass.search(params[:search])
    numclasses = @dclass.count
    if numclasses == 0
      flash[:failure] = "no classes found, please search again"
      redirect_to "/"
    else
      render 'list'
    end
  end

  def show
    @dclass = DClass.find(params[:id])
  end

  def index
    @dclass = DClass.all
  end

  

  
private

  def dclass_params
    params.require(:d_class).permit(:dancetype, :day, :location)
  end

end

danceclassappv1/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

danceclassappv1/app/helpers/application_helper.rb
module ApplicationHelper
end

danceclassappv1/app/helpers/d_class_helper.rb
module DClassHelper
end

danceclassappv1/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

danceclassappv1/app/views/d_class/index.html.erb
<h1> All dance classes </h1>

#<ul class=“dclasses”>
#  <% @dclass.each do |dclass| %>
#    <li>
#      <%= link_to dclass.dancetype, dclass %>
#      <%= dclass.day %>
#      <%= dclass.location %>
#    </li>
#  <% end %>
#</ul>

danceclassappv1/app/views/d_class/list.html.erb
<h1>DClass#list</h1>
<p>Find me in app/views/d_class/list.html.erb</p>
<p> This is going to be the page where you LIST dance classes from search result</p>

<h1> All dance classes </h1>
<p>
 <% if @dclass.empty? %>
     <p> no results, try again </p>
     <%= render "shared/searchform" %>
 <% else %>

  <% @dclass.each do |dclass| %>
    <li>
      <%= dclass.dancetype %>
      <%= dclass.day %>
      <%= dclass.location %>
    </li>
  <% end %>
 <% end %>
</p>

danceclassappv1/app/views/d_class/new.html.erb
<h1>DClass#new</h1>
<p>Find me in app/views/d_class/new.html.erb</p>
<p> This is going to be the page where you add new dance classes </p>

<h1>Add new class </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @dclass, url:d_class_index_path do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :dancetype %>
      <%= f.text_field :dancetype, class: 'form-control' %>
      <%= f.label :day %>
      <%= f.text_field :day, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.submit  %>
    <% end %>
  </div>
</div>

danceclassappv1/app/views/d_class/show.html.erb
<%= @dclass.dancetype %>, <%= @dclass.day %>, <%= @dclass.location %>

danceclassappv1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Danceclassappv1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    .
    .
    .
  </body>
</html>

danceclassappv1/app/views/shared/_error_messages.html.erb
<% if @dclass.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@dclass.errors.count, "error") %>.
    </div>
    <ul>
    <% @dclass.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

danceclassappv1/app/views/shared/_searchform.html.erb
<h1>Dance Class App</h1>
<p> Search for your dance class here </p>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag(d_class_list_path,:method => "get",id: "search-form") do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "search", :name => nil %>
    <% end %>
  </div>
</div>

danceclassappv1/app/views/static_pages/home.html.erb
<%= render "shared/searchform" %>